/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DiscordIcon: typeof import('../components/icons').DiscordIcon
  const GithubIcon: typeof import('../components/icons').GithubIcon
  const HeartFilledIcon: typeof import('../components/icons').HeartFilledIcon
  const Link: typeof import('react-router-dom').Link
  const Logo: typeof import('../components/icons').Logo
  const MoonFilledIcon: typeof import('../components/icons').MoonFilledIcon
  const NavLink: typeof import('react-router-dom').NavLink
  const Navbar: typeof import('../components/navbar').Navbar
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const SearchIcon: typeof import('../components/icons').SearchIcon
  const SunFilledIcon: typeof import('../components/icons').SunFilledIcon
  const ThemeSwitch: typeof import('../components/theme-switch').ThemeSwitch
  const TwitterIcon: typeof import('../components/icons').TwitterIcon
  const createRef: typeof import('react').createRef
  const default: typeof import('../layouts/default').default
  const forwardRef: typeof import('react').forwardRef
  const layouts: typeof import('../layouts/index').layouts
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const siteConfig: typeof import('../config/site').siteConfig
  const startTransition: typeof import('react').startTransition
  const store: typeof import('../store/index').store
  const subtitle: typeof import('../components/primitives').subtitle
  const title: typeof import('../components/primitives').title
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { SiteConfig } from '../config/site'
  import('../config/site')
  // @ts-ignore
  export type { IconSvgProps } from '../components/icons'
  import('../components/icons')
  // @ts-ignore
  export type { ThemeSwitchProps } from '../components/theme-switch'
  import('../components/theme-switch')
}
